# Generated by Django 3.2.5 on 2021-07-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt', '0002_auto_20210711_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunt',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
