# Generated by Django 3.2.5 on 2021-07-22 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0002_cartitems_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
